# Generated by Django 3.0 on 2019-12-18 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address1', models.CharField(default='', max_length=100)),
                ('Address2', models.CharField(blank=True, default='', max_length=100)),
                ('City', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=20)),
                ('Zip', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, unique=True)),
                ('AnnualRevenue', models.DecimalField(decimal_places=10, max_digits=19)),
                ('MonthlyAverageBankBalance', models.DecimalField(decimal_places=10, max_digits=12)),
                ('MonthlyAverageCreditCardVolume', models.DecimalField(decimal_places=10, max_digits=12)),
                ('TaxID', models.BigIntegerField()),
                ('Phone', models.BigIntegerField()),
                ('NAICS', models.BigIntegerField()),
                ('HasBeenProfitable', models.BooleanField()),
                ('HasBankruptedInLast7Years', models.BooleanField()),
                ('InceptionDate', models.DateField()),
                ('Business_Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Address')),
            ],
        ),
        migrations.CreateModel(
            name='CFApplicationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestedLoanAmount', models.CharField(max_length=255, unique=True)),
                ('StatedCreditHistory', models.CharField(max_length=255, unique=True)),
                ('LegalEntityType', models.CharField(max_length=255)),
                ('FilterID', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RequestHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CFRequestId', models.CharField(max_length=255)),
                ('RequestDate', models.DateField(max_length=40)),
                ('CFApiUserId', models.CharField(max_length=255)),
                ('CFApiPassword', models.CharField(max_length=20)),
                ('IsTestLead', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('DateOfBirth', models.DateField(max_length=40)),
                ('HomePhone', models.BigIntegerField()),
                ('SSN', models.BigIntegerField()),
                ('PercentageOfOwnership', models.DecimalField(decimal_places=2, max_digits=3)),
                ('HomeAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Address')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Business')),
            ],
        ),
    ]
