# Generated by Django 3.0 on 2019-12-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
