# Generated by Django 3.0 on 2019-12-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20191218_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='NAICS',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
        migrations.AlterField(
            model_name='business',
            name='Phone',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
        migrations.AlterField(
            model_name='business',
            name='TaxID',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
    ]
