# Generated by Django 3.0 on 2019-12-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20191218_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='AnnualRevenue',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='business',
            name='MonthlyAverageBankBalance',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='business',
            name='MonthlyAverageCreditCardVolume',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='business',
            name='NAICS',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='Name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='Phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='TaxID',
            field=models.BigIntegerField(),
        ),
    ]
