# Generated by Django 3.0 on 2019-12-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20191219_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='PercentageOfOwnership',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
